name: influx-db
version: "0.1-DEV"
summary: Fast and Flexible Static Site Generator
description: |
  InfluxDB is an open source time series database with no external dependencies. 
  It's useful for recording metrics, events, and performing analytics.
confinement: devmode
grade: devel # "devel" or "stable"

apps:
  influx:
    command: bin/influx
    plugs: [home, network-bind]

parts:
  influx:
    source: .
    plugin: go
    go-importpath: github.com/spartonia/influxdb
    build-packages:
      - git
      - make
    stage-packages:
      - python-pygments
    prepare: |
      export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      export PATH=$GOPATH/bin:$PATH
      cd $GOPATH/src/github.com/spartonia/influxdb
      make vendor
      make test
      rm -f $GOPATH/bin/govendor
    install: |
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/influx
    after: [go]
  go:
    source-tag: go1.8.3
